# Usage:
#
# 1. Build & start:
#      docker-compose up --build
#
# 2. Stop:
#      docker-compose down
#
# 3. Run in detached mode:
#      docker-compose up --build -d
#
# The dev server will be available at: http://localhost:5173

services:
  countdown-timer:

    # Build from the local Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Map port 5173 on host to 5173 in container
    ports:
      - '5173:5173'

    # Use polling to detect file changes in the container under Windows hosts.
    # See https://vite.dev/config/server-options#server-watch.
    env:
      - CHOKIDAR_USEPOLLING=true

    # Mount source code for live reload
    volumes:
      - ./:/app
      # Prevent host's node_modules from overriding container's install:
      - /app/node_modules

    restart: unless-stopped
